//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string CreateElection_CancelBtn {
            get {
                return ResourceManager.GetString("CreateElection_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string CreateElection_CreateBtn {
            get {
                return ResourceManager.GetString("CreateElection_CreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string CreateElection_Description {
            get {
                return ResourceManager.GetString("CreateElection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окончание выборов.
        /// </summary>
        public static string CreateElection_End {
            get {
                return ResourceManager.GetString("CreateElection_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название выборов.
        /// </summary>
        public static string CreateElection_Name {
            get {
                return ResourceManager.GetString("CreateElection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало выборов.
        /// </summary>
        public static string CreateElection_Start {
            get {
                return ResourceManager.GetString("CreateElection_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Создать выборы.
        /// </summary>
        public static string CreateElection_Title {
            get {
                return ResourceManager.GetString("CreateElection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список актуальных выборов.
        /// </summary>
        public static string ElectionsIndex_ActualList {
            get {
                return ResourceManager.GetString("ElectionsIndex_ActualList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новые выборы.
        /// </summary>
        public static string ElectionsIndex_Create {
            get {
                return ResourceManager.GetString("ElectionsIndex_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string ElectionsIndex_Delete {
            get {
                return ResourceManager.GetString("ElectionsIndex_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string ElectionsIndex_Description {
            get {
                return ResourceManager.GetString("ElectionsIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string ElectionsIndex_Edit {
            get {
                return ResourceManager.GetString("ElectionsIndex_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время окончания.
        /// </summary>
        public static string ElectionsIndex_End {
            get {
                return ResourceManager.GetString("ElectionsIndex_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться на главную.
        /// </summary>
        public static string ElectionsIndex_GoBackBtn {
            get {
                return ResourceManager.GetString("ElectionsIndex_GoBackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер выборов.
        /// </summary>
        public static string ElectionsIndex_Id {
            get {
                return ResourceManager.GetString("ElectionsIndex_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string ElectionsIndex_Name {
            get {
                return ResourceManager.GetString("ElectionsIndex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет зарегистрированных выборов.
        /// </summary>
        public static string ElectionsIndex_NoActual {
            get {
                return ResourceManager.GetString("ElectionsIndex_NoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала.
        /// </summary>
        public static string ElectionsIndex_Start {
            get {
                return ResourceManager.GetString("ElectionsIndex_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избирательный центр.
        /// </summary>
        public static string ElectionsIndex_Title {
            get {
                return ResourceManager.GetString("ElectionsIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть.
        /// </summary>
        public static string ElectionsIndex_View {
            get {
                return ResourceManager.GetString("ElectionsIndex_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть архивные выборы.
        /// </summary>
        public static string ElectionsIndex_ViewArchive {
            get {
                return ResourceManager.GetString("ElectionsIndex_ViewArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст.
        /// </summary>
        public static string FullProfile_Age {
            get {
                return ResourceManager.GetString("FullProfile_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать пользователя.
        /// </summary>
        public static string FullProfile_CreateUser {
            get {
                return ResourceManager.GetString("FullProfile_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FullProfile_Name {
            get {
                return ResourceManager.GetString("FullProfile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный профиль.
        /// </summary>
        public static string FullProfile_Title {
            get {
                return ResourceManager.GetString("FullProfile_Title", resourceCulture);
            }
        }
    }
}
