// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.EfStuff;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(KzDbContext))]
    partial class KzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.EfStuff.Model.BronResto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BronRespNumber")
                        .HasColumnType("int");

                    b.Property<int>("CountOfVisitors")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfVisitors")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTables")
                        .HasColumnType("int");

                    b.Property<string>("PhUserNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RestoransesId")
                        .HasColumnType("bigint");

                    b.Property<bool>("StateReservation")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RestoransesId");

                    b.ToTable("BronResto");
                });

            modelBuilder.Entity("WebApplication1.EfStuff.Model.Restorans", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Access")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AverageCheck")
                        .HasColumnType("int");

                    b.Property<bool>("DanceFloor")
                        .HasColumnType("bit");

                    b.Property<bool>("Karaoke")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTables")
                        .HasColumnType("int");

                    b.Property<bool>("Parking")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WiFi")
                        .HasColumnType("bit");

                    b.Property<string>("Сuisine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restorans");
                });

            modelBuilder.Entity("WebApplication1.EfStuff.Model.BronResto", b =>
                {
                    b.HasOne("WebApplication1.EfStuff.Model.Restorans", "Restoranses")
                        .WithMany("Brons")
                        .HasForeignKey("RestoransesId");

                    b.Navigation("Restoranses");
                });

            modelBuilder.Entity("WebApplication1.EfStuff.Model.Restorans", b =>
                {
                    b.Navigation("Brons");
                });
#pragma warning restore 612, 618
        }
    }
}
